name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "fc762d7a-89fd-4095-b409-ec7b22a84db7"      # 替换为你创建的数据库 ID
